// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_app_backend.Data;

namespace Trainee_app_backend.Migrations
{
    [DbContext(typeof(GmfctnContext))]
    [Migration("20210406190006_resolving")]
    partial class resolving
    {
    }
}
